version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  routing-service:
    build: .
    container_name: routing-service
    ports:
      - "3002:3002"
    depends_on:
      - redis
    environment:
      - .env