apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routing-service
  template:
    metadata:
      labels:
        app: routing-service
    spec:
      containers:
        - name: routing-service
          image: routing-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: REDIS_HOST
              value: redis
            - name: AUDIT_SERVICE_URL
              value: http://localhost:3003/alert
            - name: REDIS_TTL_SECONDS
              value: "300"
              
apiVersion: v1
kind: Service
metadata:
  name: routing-service
spec:
  selector:
    app: routing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
