apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routing-service
  template:
    metadata:
      labels:
        app: routing-service
    spec:
      containers:
        - name: routing-service
          image: routing-service-routing-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: REDIS_HOST
              value: redis
            - name: AUDIT_SERVICE_URL
              value: http://audit-service:3000
            - name: REDIS_TTL_SECONDS
              value: "300"
